import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 폴더 구조 그대로 사이드바가 된다 — 각 폴더의 _category_.json 이 라벨·순서를 정한다.
// 새 문서를 추가·이동해도 여기(sidebars.ts)는 손댈 필요가 없다.
// (예전 porest-docs 는 config.ts 에 ko/en 사이드바를 손으로 두 벌 하드코딩해서
//  페이지를 옮길 때마다 두 곳이 어긋났다 — 여기선 그 문제 자체가 없다.)
const sidebars: SidebarsConfig = {
  guideSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
